FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate && npm run build

EXPOSE 5001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/index.js"]
