services:
  postgres:
    image: postgres:15
    container_name: devtasks-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devtasks
      POSTGRES_PASSWORD: devtasks123
      POSTGRES_DB: devtasks
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
